name: pa55
description: A reference implementation of PA55 (not PA55 NYAPS) in Dart.
version: 1.0.0
homepage: https://github.com/pa55/pa55-dart/
author: Anirban Basu

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  pointycastle: ^1.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
